server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/diudiu?useSSL=false&useUnicode=true&characterEncoding=utf-8&TIMEZONE=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
oss:
  accessKey: AVUQ7IxmT6TgBfoSjW4qUGvCJEKUrcmLDaXzm0Xo
  secretKey: qs5tM4VW9_NTMnQehSUNOlUnIa-0XgC2i4bs1jld
  bucket: rikka-picture
  link: http://ayaka.ayaka.fun/